{ config, lib, pkgs, vars, ... }:
{
    hardware = {
        amdgpu.initrd.enable = true;
        cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; # Autogenerated
    };
    boot = {
        initrd = {
            # Drivers preloading
            kernelModules = /*lib.unique ((config.boot.initrd.kernelModules or []) ++*/ [ "amdgpu" ];
            availableKernelModules = /*lib.unique ((config.boot.initrd.availableKernelModules or []) ++*/ [ "amdgpu" ];
        };
        kernelParams = /*lib.unique ((config.boot.kernelParams or []) ++*/ [
            "amd_pstate=active"  # Optimizing processor perfomance mode
            "random.trust_cpu=1" # Disable using the entripy (the loading will speed up)
        ];

        kernelModules = /*lib.unique ((config.boot.kernelModules or []) ++*/ [ "kvm-amd" ]; # Autogenerated
    };

    services.xserver.videoDrivers = /*lib.unique ((config.services.xserver.videoDrivers or []) ++*/ [ "amdgpu" ];
}
